alternate: 阿克夏书馆主馆

# Assets
statics: /

open_graph:

menu:
  home: / || home
  about:
    default: / || user
    zishe: /zishe/ || cloud
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  website:
    default: / || magic
    friends: /friends/ || heart
    webstack: /webstack/ || star
  links: https://californiafinch.github.io || paper-plane

# Social Links
social:
  github: https://github.com/californiafitzleo || github || "#191717"
  music: https://music.163.com/#/user/home?id=2127251074 || cloud-music || "#e60026"
  email: mailto:california_fitz@outlook.com || envelope || "#ec8c69"

# Dark Mode
darkmode: false

# 自动定位
auto_scroll: false

# 加载动画
loader:
  start: true
  switch: true

# 页面特效
fireworks:
  enable: true

# 字体配置
font:
  enable: true
  global:
    external: true
    family: Mulish
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5
  title:
    external: true
    family: Noto Serif JP
    size: 2.5
  headings:
    external: true
    family: Noto Serif SC
  codes:
    external: true
    family: Inconsolata

# iconfont
iconfont: "1832207_igi8uaupcus"

# 边栏
sidebar:
  position: right
  avatar: avatar.jpg

# 底部
widgets:
  random_posts: true
  recent_comments: false

# 字数及阅读时间统计
footer:
  since: 2010
  icon:
    name: sakura rotate
    color: "#ffc0cb"
  count: true
  powered: true

post:
  count: true

# Reward (Donate)
reward:
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png

# TagCloud
tagcloud:
  min: 16
  max: 22
  start: "#72cecf"
  end: "#ffbac3"
  amount: 200

# Creative Commons
creative_commons:
  license: by-nc-sa
  language: zh-CN

# Comments - 请在 LeanCloud 注册后填写
valine:
  appId: 
  appKey: 
  placeholder: ヽ(○´∀`)ﾉ♪
  pageSize: 10
  lang: zh-CN

# bgm
audio:
  - title: love music
    list:
      - https://music.163.com/#/playlist?id=10125816643

# pangu 中文排版
pangu: true

# Quicklink
quicklink:
  timeout: 3000
  priority: true

# analytics & SEO
baidu_analytics:
disable_baidu_transformation: true
exturl: true
google_site_verification:
bing_site_verification:
baidu_site_verification:
baidu_push: false

# minify
minify:
  html:
    enable: true
    exclude:
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
      toplevel: true
    exclude:
      - '**/*.min.js'

# 代码高亮
highlight:
  enable: false

prismjs:
  enable: false

# feed
feed:
  limit: 20
  order_by: "-date"
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: "themes/shoka/layout/_alternate/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "themes/shoka/layout/_alternate/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "themes/shoka/layout/_alternate/json.ejs"
    output: "feed.json"
